### ISSUE TITLE
update to newton 3.14c

### ISSUE THREAD

**Issue by netpipe** [raffaem/irrnewt#1]
standardize source builds with emscripten cmake compatability. was thinking either of these versions though 3.14 compiles with less issues. https://github.com/MADEAPPS/newton-dynamics

**Comment by raffaelemancuso** [comment]
Hello,

Thank you very much for your interest in the project.

The project is abandoned from my part. I coded it many years ago, I don't even remember which Newton version it uses. I have no time and honestly no more interest to work on it right now.

If you would like to work on it and support it, I would be happy to provide you all the permissions you need.

Thank you again for your interest in the project.

Best regards

**Comment by raffaelemancuso** [comment]
I am going to archive this

Feel free to fork and update it as you wish
